audio = []
date = "2020-07-06"
description =  "A little while ago, I was having a discussion with my friends in which we attempted to identify the landmark moments in music that defined the last decade. One thing we all agreed upon was that Old Town Road by Lil Nas X was a cultural touchstone that careered though the musical landscape."
images = ["logo.png"]
series = []
tags = []
title = "Old Town Road: Yee Haw Utopia"
videos = []
